[package]
name = "common_db"
version = "0.1.0"
edition = "2021"

[dependencies]
common = {path = "../common"}
sqlx = { version = "0.8", features = ["mysql","tls-rustls", "default","chrono","runtime-tokio"] }


[features]
default = []
net = ["common/net"]